# Exportar todos los routers
from . import (
    alerts,
    analysis,
    audit,
    certificates,
    citizen,
    contact,
    episodes,
    explorations,
    fire_events,
    fires,
    historical,
    imagery,
    metrics,
    monitoring,
    payments,
    quality,
    reports,
    visitor_logs,
    webhooks,
    workers,
    tasks,
)

__all__ = [
    "fires",
    "explorations",
    "audit",
    "certificates",
    "monitoring",
    "fire_events",
    "reports",
    "payments",
    "webhooks",
    "citizen",
    "contact",
    "quality",
    "analysis",
    "historical",
    "imagery",
    "metrics",
    "workers",
    "alerts",
    "visitor_logs",
    "episodes",
    "tasks",
]
