-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alembic_version (
  version_num character varying NOT NULL,
  CONSTRAINT alembic_version_pkey PRIMARY KEY (version_num)
);
CREATE TABLE public.audit_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  principal_id character varying,
  principal_role character varying,
  action character varying NOT NULL CHECK (length(action::text) > 0),
  resource_type character varying,
  resource_id uuid,
  details jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.burn_certificates (
  fire_event_id uuid NOT NULL,
  issued_to character varying NOT NULL,
  requester_email character varying,
  certificate_number character varying NOT NULL UNIQUE,
  data_hash character varying NOT NULL UNIQUE,
  snapshot_data text NOT NULL,
  verification_url character varying,
  issued_at timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone,
  status character varying,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT burn_certificates_pkey PRIMARY KEY (id),
  CONSTRAINT burn_certificates_fire_event_id_fkey FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id)
);
CREATE TABLE public.citizen_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reported_location USER-DEFINED NOT NULL,
  reported_latitude double precision NOT NULL,
  reported_longitude double precision NOT NULL,
  location_description text,
  report_type character varying,
  description text NOT NULL,
  observed_date date,
  user_photos ARRAY,
  reporter_name character varying,
  reporter_email character varying,
  reporter_phone character varying,
  is_anonymous boolean DEFAULT false,
  reporter_organization character varying,
  related_fire_events ARRAY,
  related_protected_areas ARRAY,
  historical_fires_in_area integer,
  evidence_package_url text,
  status character varying DEFAULT 'submitted'::character varying,
  reviewed_by character varying,
  reviewed_at timestamp with time zone,
  authority_notified character varying,
  authority_notified_at timestamp with time zone,
  internal_notes text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reporter_user_id uuid DEFAULT auth.uid(),
  CONSTRAINT citizen_reports_pkey PRIMARY KEY (id),
  CONSTRAINT citizen_reports_reporter_user_id_fkey FOREIGN KEY (reporter_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.climate_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location USER-DEFINED NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  recorded_at timestamp with time zone NOT NULL,
  data_source character varying NOT NULL DEFAULT 'open-meteo'::character varying,
  source_dataset character varying,
  temperature_2m numeric,
  relative_humidity_2m numeric,
  wind_speed_10m numeric,
  wind_direction_10m integer,
  wind_gusts_10m numeric,
  precipitation numeric,
  soil_moisture_0_to_10cm numeric,
  evapotranspiration numeric,
  vapor_pressure_deficit numeric,
  fire_weather_index numeric,
  drought_code numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT climate_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clustering_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  version_name character varying NOT NULL,
  epsilon_km numeric NOT NULL CHECK (epsilon_km > 0::numeric AND epsilon_km <= 100::numeric),
  min_points integer NOT NULL CHECK (min_points >= 1 AND min_points <= 100),
  temporal_window_hours integer NOT NULL CHECK (temporal_window_hours >= 1 AND temporal_window_hours <= 168),
  algorithm character varying NOT NULL DEFAULT 'ST-DBSCAN'::character varying CHECK (algorithm::text = ANY (ARRAY['DBSCAN'::character varying, 'ST-DBSCAN'::character varying, 'HDBSCAN'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  is_active boolean DEFAULT true,
  change_reason text,
  CONSTRAINT clustering_versions_pkey PRIMARY KEY (id),
  CONSTRAINT clustering_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.credit_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  amount integer NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['purchase'::character varying, 'grant'::character varying, 'spend'::character varying, 'refund'::character varying, 'expiration'::character varying, 'adjustment'::character varying]::text[])),
  payment_request_id uuid,
  related_entity_type character varying,
  related_entity_id uuid,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT credit_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT credit_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT credit_transactions_payment_request_id_fkey FOREIGN KEY (payment_request_id) REFERENCES public.payment_requests(id)
);
CREATE TABLE public.data_source_metadata (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_name character varying NOT NULL UNIQUE,
  source_type character varying NOT NULL CHECK (source_type::text = ANY (ARRAY['satellite_detection'::character varying, 'satellite_imagery'::character varying, 'climate'::character varying, 'administrative'::character varying, 'derived'::character varying]::text[])),
  provider character varying NOT NULL,
  provider_url text,
  api_endpoint text,
  spatial_resolution_meters integer,
  temporal_resolution_hours integer,
  update_frequency character varying,
  coverage_description text,
  coverage_start_date date,
  accuracy_description text,
  known_limitations ARRAY,
  confidence_baseline numeric,
  quality_weight numeric DEFAULT 0.25 CHECK (quality_weight >= 0::numeric AND quality_weight <= 1::numeric),
  is_active boolean DEFAULT true,
  last_validated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_source_metadata_pkey PRIMARY KEY (id)
);
CREATE TABLE public.episode_mergers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  absorbed_episode_id uuid NOT NULL,
  absorbing_episode_id uuid NOT NULL,
  merged_at timestamp with time zone DEFAULT now(),
  reason character varying NOT NULL CHECK (reason::text = ANY (ARRAY['spatial_overlap'::character varying, 'temporal_continuity'::character varying, 'manual_merge'::character varying, 'algorithm_update'::character varying]::text[])),
  merged_by_version_id uuid,
  notes text,
  CONSTRAINT episode_mergers_pkey PRIMARY KEY (id),
  CONSTRAINT episode_mergers_absorbing_episode_id_fkey FOREIGN KEY (absorbing_episode_id) REFERENCES public.fire_episodes(id),
  CONSTRAINT episode_mergers_merged_by_version_id_fkey FOREIGN KEY (merged_by_version_id) REFERENCES public.clustering_versions(id),
  CONSTRAINT episode_mergers_absorbed_episode_id_fkey FOREIGN KEY (absorbed_episode_id) REFERENCES public.fire_episodes(id)
);
CREATE TABLE public.fire_climate_associations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fire_event_id uuid NOT NULL,
  climate_data_id uuid NOT NULL,
  association_type character varying NOT NULL DEFAULT 'during'::character varying CHECK (association_type::text = ANY (ARRAY['before'::character varying, 'during'::character varying, 'after'::character varying, 'peak'::character varying]::text[])),
  hours_offset integer,
  distance_km numeric,
  relevance_weight numeric DEFAULT 1.0 CHECK (relevance_weight >= 0::numeric AND relevance_weight <= 1::numeric),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fire_climate_associations_pkey PRIMARY KEY (id),
  CONSTRAINT fire_climate_associations_fire_event_id_fkey FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id),
  CONSTRAINT fire_climate_associations_climate_data_id_fkey FOREIGN KEY (climate_data_id) REFERENCES public.climate_data(id)
);
CREATE TABLE public.fire_detections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  satellite character varying NOT NULL,
  instrument character varying NOT NULL,
  detected_at timestamp with time zone NOT NULL,
  location USER-DEFINED NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  bt_mir_kelvin numeric,
  bt_tir_kelvin numeric,
  fire_radiative_power numeric,
  confidence_raw character varying,
  confidence_normalized integer,
  acquisition_date date,
  acquisition_time time without time zone,
  daynight character varying,
  is_processed boolean DEFAULT false,
  fire_event_id uuid,
  h3_index bigint,
  CONSTRAINT fire_detections_pkey PRIMARY KEY (id),
  CONSTRAINT fire_detections_fire_event_id_fkey FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id)
);
CREATE TABLE public.fire_episode_events (
  episode_id uuid NOT NULL,
  event_id uuid NOT NULL,
  added_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fire_episode_events_pkey PRIMARY KEY (episode_id, event_id),
  CONSTRAINT fire_episode_events_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES public.fire_episodes(id),
  CONSTRAINT fire_episode_events_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.fire_events(id)
);
CREATE TABLE public.fire_episodes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'monitoring'::character varying, 'extinct'::character varying, 'closed'::character varying]::text[])),
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  centroid_lat numeric,
  centroid_lon numeric,
  bbox_minx numeric,
  bbox_miny numeric,
  bbox_maxx numeric,
  bbox_maxy numeric,
  provinces ARRAY,
  event_count integer DEFAULT 0,
  detection_count integer DEFAULT 0,
  frp_sum numeric,
  frp_max numeric,
  estimated_area_hectares numeric,
  gee_candidate boolean DEFAULT false,
  gee_priority integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  clustering_version_id uuid,
  requires_recalculation boolean DEFAULT false,
  dnbr_severity numeric,
  severity_class character varying,
  dnbr_calculated_at timestamp with time zone,
  last_gee_image_id character varying,
  last_update_sat timestamp with time zone,
  slides_data jsonb,
  last_seen_at timestamp with time zone,
  extinct_at timestamp with time zone,
  CONSTRAINT fire_episodes_pkey PRIMARY KEY (id),
  CONSTRAINT fire_episodes_clustering_version_id_fkey FOREIGN KEY (clustering_version_id) REFERENCES public.clustering_versions(id)
);
CREATE TABLE public.fire_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  centroid USER-DEFINED NOT NULL,
  perimeter USER-DEFINED,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  total_detections integer,
  avg_frp numeric,
  max_frp numeric,
  sum_frp numeric,
  avg_confidence numeric,
  estimated_area_hectares numeric,
  province character varying,
  department character varying,
  is_significant boolean,
  processing_error character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  has_legal_analysis boolean DEFAULT false,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'monitoring'::character varying, 'extinct'::character varying]::text[])),
  extinct_at timestamp with time zone,
  last_gee_image_id character varying,
  last_update_sat timestamp with time zone,
  slides_data jsonb DEFAULT '[]'::jsonb,
  has_historic_report boolean DEFAULT false,
  h3_index bigint,
  clustering_version_id uuid,
  last_seen_at timestamp with time zone,
  CONSTRAINT fire_events_pkey PRIMARY KEY (id),
  CONSTRAINT fire_events_clustering_version_id_fkey FOREIGN KEY (clustering_version_id) REFERENCES public.clustering_versions(id)
);
CREATE TABLE public.fire_protected_area_intersections (
  fire_event_id uuid NOT NULL,
  protected_area_id uuid NOT NULL,
  intersection_geometry USER-DEFINED,
  intersection_area_hectares double precision,
  overlap_percentage double precision,
  fire_date date NOT NULL,
  prohibition_until date NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fire_protected_area_intersections_pkey PRIMARY KEY (id),
  CONSTRAINT fire_protected_area_intersections_fire_event_id_fkey FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id),
  CONSTRAINT fire_protected_area_intersections_protected_area_id_fkey FOREIGN KEY (protected_area_id) REFERENCES public.protected_areas(id)
);
CREATE TABLE public.fire_stats_refresh_state (
  id integer NOT NULL,
  fail_count integer NOT NULL DEFAULT 0,
  last_error text,
  last_run_at timestamp with time zone,
  next_run_at timestamp with time zone,
  CONSTRAINT fire_stats_refresh_state_pkey PRIMARY KEY (id)
);
CREATE TABLE public.forensic_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fire_event_id uuid NOT NULL,
  protected_area_id uuid NOT NULL,
  burned_area_hectares numeric NOT NULL,
  overlap_percentage numeric NOT NULL,
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'analyzing'::character varying, 'confirmed_violation'::character varying, 'dismissed'::character varying]::text[])),
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  final_verdict text,
  assigned_auditor character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT forensic_cases_pkey PRIMARY KEY (id),
  CONSTRAINT fk_forensic_fire FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id),
  CONSTRAINT fk_forensic_pa FOREIGN KEY (protected_area_id) REFERENCES public.protected_areas(id)
);
CREATE TABLE public.hd_generation_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  investigation_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'queued'::character varying CHECK (status::text = ANY (ARRAY['queued'::character varying, 'processing'::character varying, 'ready'::character varying, 'failed'::character varying]::text[])),
  progress_total integer NOT NULL DEFAULT 0,
  progress_done integer NOT NULL DEFAULT 0,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  idempotency_key text,
  results jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT hd_generation_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT hd_generation_jobs_investigation_id_fkey FOREIGN KEY (investigation_id) REFERENCES public.user_investigations(id)
);
CREATE TABLE public.idempotency_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  idempotency_key character varying NOT NULL,
  endpoint character varying NOT NULL,
  request_hash character varying NOT NULL,
  response_status_code integer,
  response_body jsonb,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval),
  CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.investigation_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  investigation_item_id uuid NOT NULL,
  gcs_path text NOT NULL,
  signed_url_cache jsonb,
  mime text,
  width integer,
  height integer,
  sha256 text,
  generated_at timestamp with time zone,
  recipe jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT investigation_assets_pkey PRIMARY KEY (id),
  CONSTRAINT investigation_assets_investigation_item_id_fkey FOREIGN KEY (investigation_item_id) REFERENCES public.investigation_items(id)
);
CREATE TABLE public.investigation_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  investigation_id uuid NOT NULL,
  kind character varying NOT NULL CHECK (kind::text = ANY (ARRAY['pre'::character varying, 'post'::character varying]::text[])),
  target_date timestamp with time zone NOT NULL,
  sensor character varying,
  aoi jsonb,
  geometry_ref text,
  visualization_params jsonb,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'queued'::character varying, 'generated'::character varying, 'failed'::character varying]::text[])),
  error text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT investigation_items_pkey PRIMARY KEY (id),
  CONSTRAINT investigation_items_investigation_id_fkey FOREIGN KEY (investigation_id) REFERENCES public.user_investigations(id)
);
CREATE TABLE public.investigation_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  investigation_id uuid NOT NULL,
  share_token uuid NOT NULL DEFAULT gen_random_uuid(),
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT investigation_shares_pkey PRIMARY KEY (id),
  CONSTRAINT investigation_shares_investigation_id_fkey FOREIGN KEY (investigation_id) REFERENCES public.user_investigations(id)
);
CREATE TABLE public.land_use_audits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  queried_latitude double precision NOT NULL,
  queried_longitude double precision NOT NULL,
  queried_location USER-DEFINED,
  search_radius_meters integer,
  fires_found integer DEFAULT 0,
  is_violation boolean DEFAULT false,
  violation_severity character varying,
  prohibition_until date,
  earliest_fire_date date,
  latest_fire_date date,
  user_ip inet,
  user_agent text,
  query_duration_ms integer,
  queried_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT land_use_audits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.land_use_changes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fire_event_id uuid NOT NULL,
  monitoring_record_id uuid,
  change_detected_at date NOT NULL,
  months_after_fire integer,
  change_type character varying NOT NULL,
  change_severity character varying,
  before_image_id uuid,
  after_image_id uuid,
  change_detection_image_url text,
  affected_area_hectares double precision,
  is_potential_violation boolean DEFAULT false,
  violation_confidence character varying,
  status character varying DEFAULT 'pending_review'::character varying,
  reviewed_by character varying,
  reviewed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT land_use_changes_pkey PRIMARY KEY (id),
  CONSTRAINT land_use_changes_fire_event_id_fkey FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id)
);
CREATE TABLE public.payment_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'expired'::character varying, 'refunded'::character varying]::text[])),
  provider character varying NOT NULL DEFAULT 'mercadopago'::character varying CHECK (provider::text = ANY (ARRAY['mercadopago'::character varying, 'manual'::character varying, 'promotional'::character varying]::text[])),
  purpose character varying NOT NULL CHECK (purpose::text = ANY (ARRAY['report'::character varying, 'credits'::character varying]::text[])),
  target_entity_type character varying,
  target_entity_id uuid,
  amount_usd numeric NOT NULL,
  amount_ars numeric,
  external_reference character varying NOT NULL UNIQUE,
  provider_payment_id character varying,
  provider_preference_id character varying,
  checkout_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  approved_at timestamp with time zone,
  webhook_received_at timestamp with time zone,
  retry_count integer NOT NULL DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT payment_requests_pkey PRIMARY KEY (id),
  CONSTRAINT payment_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_webhook_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_request_id uuid,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  topic character varying,
  action character varying,
  mp_payment_id character varying,
  raw_payload jsonb NOT NULL,
  processing_result character varying CHECK (processing_result::text = ANY (ARRAY['success'::character varying, 'ignored'::character varying, 'error'::character varying, 'duplicate'::character varying]::text[])),
  error_message text,
  processing_time_ms integer,
  CONSTRAINT payment_webhook_logs_pkey PRIMARY KEY (id),
  CONSTRAINT payment_webhook_logs_payment_request_id_fkey FOREIGN KEY (payment_request_id) REFERENCES public.payment_requests(id)
);
CREATE TABLE public.protected_areas (
  official_name character varying NOT NULL,
  alternative_names ARRAY,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['national_park'::character varying, 'national_reserve'::character varying, 'natural_monument'::character varying, 'provincial_reserve'::character varying, 'provincial_park'::character varying, 'biosphere_reserve'::character varying, 'ramsar_site'::character varying, 'world_heritage'::character varying, 'municipal_reserve'::character varying, 'private_reserve'::character varying, 'wildlife_refuge'::character varying, 'marine_park'::character varying, 'other'::character varying]::text[])),
  boundary USER-DEFINED NOT NULL,
  simplified_boundary USER-DEFINED,
  centroid USER-DEFINED,
  area_hectares double precision,
  jurisdiction character varying CHECK (jurisdiction IS NULL OR (jurisdiction::text = ANY (ARRAY['national'::character varying, 'provincial'::character varying, 'municipal'::character varying, 'private'::character varying]::text[]))),
  province character varying,
  department character varying,
  prohibition_years integer NOT NULL CHECK (prohibition_years = ANY (ARRAY[30, 60])),
  established_date date,
  managing_authority character varying,
  wdpa_id integer UNIQUE,
  iucn_category character varying,
  source_dataset character varying,
  source_url text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  carrying_capacity integer,
  CONSTRAINT protected_areas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.recovery_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  forensic_case_id uuid NOT NULL,
  year_analyzed integer NOT NULL,
  avg_ndvi numeric,
  avg_nbr numeric,
  detected_class USER-DEFINED,
  thumbnail_url text,
  satellite_image_url text,
  analyzed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT recovery_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT fk_metrics_case FOREIGN KEY (forensic_case_id) REFERENCES public.forensic_cases(id)
);
CREATE TABLE public.regions (
  id integer NOT NULL DEFAULT nextval('regions_id_seq'::regclass),
  name character varying NOT NULL,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['PROVINCIA'::character varying, 'DEPARTAMENTO'::character varying, 'MUNICIPIO'::character varying]::text[])),
  geom USER-DEFINED NOT NULL,
  CONSTRAINT regions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.satellite_images (
  fire_event_id uuid,
  satellite character varying,
  tile_id character varying,
  product_id character varying,
  acquisition_date date NOT NULL,
  acquisition_time time without time zone,
  days_after_fire integer,
  image_type character varying,
  cloud_cover_pct real,
  quality_score character varying,
  usable_for_analysis boolean,
  r2_bucket character varying,
  r2_key text NOT NULL,
  r2_url text NOT NULL,
  thumbnail_url text,
  file_size_mb real,
  bands_included ARRAY,
  processing_level character varying,
  spatial_resolution_meters smallint,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  gee_system_index character varying,
  visualization_params jsonb,
  is_reproducible boolean DEFAULT false,
  episode_id uuid,
  CONSTRAINT satellite_images_pkey PRIMARY KEY (id),
  CONSTRAINT satellite_images_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES public.fire_episodes(id),
  CONSTRAINT satellite_images_fire_event_id_fkey FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.system_parameters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  param_key character varying NOT NULL UNIQUE,
  param_value jsonb NOT NULL,
  description text,
  category character varying DEFAULT 'general'::character varying CHECK (category::text = ANY (ARRAY['general'::character varying, 'audit'::character varying, 'imagery'::character varying, 'reports'::character varying, 'clustering'::character varying, 'notifications'::character varying, 'limits'::character varying]::text[])),
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  previous_values jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT system_parameters_pkey PRIMARY KEY (id),
  CONSTRAINT system_parameters_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.user_credits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  balance integer NOT NULL DEFAULT 0 CHECK (balance >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_credits_pkey PRIMARY KEY (id),
  CONSTRAINT user_credits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_investigations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text,
  fire_event_id uuid,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'quoted'::character varying, 'processing'::character varying, 'ready'::character varying, 'failed'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_investigations_pkey PRIMARY KEY (id),
  CONSTRAINT user_investigations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_investigations_fire_event_id_fkey FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id)
);
CREATE TABLE public.user_saved_filters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  filter_name character varying NOT NULL,
  filter_config jsonb NOT NULL,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  use_count integer DEFAULT 0,
  CONSTRAINT user_saved_filters_pkey PRIMARY KEY (id),
  CONSTRAINT user_saved_filters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying,
  dni character varying UNIQUE,
  full_name character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'user'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'user'::character varying]::text[])),
  google_id character varying UNIQUE,
  avatar_url character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login_at timestamp with time zone,
  is_verified boolean NOT NULL DEFAULT false,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  deletion_reason character varying,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vegetation_monitoring (
  fire_event_id uuid NOT NULL,
  satellite_image_id uuid,
  month_number smallint,
  monitoring_date date NOT NULL,
  months_after_fire integer,
  ndvi_mean real,
  ndvi_min real,
  ndvi_max real,
  ndvi_std_dev real,
  baseline_ndvi real,
  recovery_percentage real,
  land_use_classification character varying,
  classification_confidence real,
  classification_method character varying,
  human_activity_detected boolean,
  activity_type character varying,
  activity_confidence character varying,
  notes text,
  analyst_name character varying,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vegetation_monitoring_pkey PRIMARY KEY (id),
  CONSTRAINT vegetation_monitoring_fire_event_id_fkey FOREIGN KEY (fire_event_id) REFERENCES public.fire_events(id),
  CONSTRAINT vegetation_monitoring_satellite_image_id_fkey FOREIGN KEY (satellite_image_id) REFERENCES public.satellite_images(id)
);