"""create_satellite_images_table

Revision ID: 5629d6e731ff
Revises: 
Create Date: 2026-01-31 10:47:34.959969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5629d6e731ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_images',
    sa.Column('fire_event_id', sa.UUID(), nullable=False),
    sa.Column('satellite', sa.String(length=20), nullable=True),
    sa.Column('tile_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('acquisition_time', sa.Time(), nullable=True),
    sa.Column('days_after_fire', sa.Integer(), nullable=True),
    sa.Column('image_type', sa.String(length=20), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(precision=1), nullable=True),
    sa.Column('quality_score', sa.String(length=20), nullable=True),
    sa.Column('usable_for_analysis', sa.Boolean(), nullable=True),
    sa.Column('r2_bucket', sa.String(length=100), nullable=True),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('r2_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('file_size_mb', sa.Float(precision=2), nullable=True),
    sa.Column('bands_included', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('processing_level', sa.String(length=10), nullable=True),
    sa.Column('spatial_resolution_meters', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fire_event_id'], ['fire_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vegetation_monitoring',
    sa.Column('fire_event_id', sa.UUID(), nullable=False),
    sa.Column('satellite_image_id', sa.UUID(), nullable=True),
    sa.Column('month_number', sa.SmallInteger(), nullable=True),
    sa.Column('monitoring_date', sa.Date(), nullable=False),
    sa.Column('months_after_fire', sa.Integer(), nullable=True),
    sa.Column('ndvi_mean', sa.Float(precision=3), nullable=True),
    sa.Column('ndvi_min', sa.Float(precision=3), nullable=True),
    sa.Column('ndvi_max', sa.Float(precision=3), nullable=True),
    sa.Column('ndvi_std_dev', sa.Float(precision=3), nullable=True),
    sa.Column('baseline_ndvi', sa.Float(precision=3), nullable=True),
    sa.Column('recovery_percentage', sa.Float(precision=2), nullable=True),
    sa.Column('land_use_classification', sa.String(length=50), nullable=True),
    sa.Column('classification_confidence', sa.Float(precision=2), nullable=True),
    sa.Column('classification_method', sa.String(length=50), nullable=True),
    sa.Column('human_activity_detected', sa.Boolean(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('activity_confidence', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analyst_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fire_event_id'], ['fire_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['satellite_image_id'], ['satellite_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vegetation_monitoring_human_activity_detected'), 'vegetation_monitoring', ['human_activity_detected'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vegetation_monitoring_human_activity_detected'), table_name='vegetation_monitoring')
    op.drop_table('vegetation_monitoring')
    op.drop_table('satellite_images')
    # ### end Alembic commands ###
